{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "alucard.serviceAccountName" . }}
  labels:
    {{- include "alucard.labels" . | nindent 4 }}
  {{- with .Values.annotations.serviceaccount }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}