apiVersion: v2
name: alucard
description: A Helm chart to manage deployment Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.4

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "alucard"
kubeVersion: ">= 1.23.0-0"

# Other Customizeable
home: https://alucard.thanos.my.id
icon: https://sithanos.github.io/alucard/assets/alucard.png

# Keywords
keywords:
  - kubernetes
  - helm
  - alucard
  - krew
  - infrastructure
  - container
  - images
  - argo
  - flux
  - google
  - amazon
  - chart
  - thanos
  - aws
  - gcp
  - application
  - app
  - latest

# Annotations
annotations:
  artifacthub.io/alternativeName: alucard
  artifacthub.io/category: integration-delivery
  artifacthub.io/changes: |
    - kind: fixed
      description: Update values.yaml information
      links:
        - name: GitHub Repository
          url: https://sithanos.github.io/alucard/alucard/values.yaml
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: source
      url: https://sithanos.github.io/alucard
    - name: support
      url: https://thanos.my.id 
  artifacthub.io/maintainers: |
    - name: sithanos
      email: hello@thanos.my.id
    - name: xhilmi
      email: hilmiafifi12@gmail.com    
  artifacthub.io/signKey: |
    fingerprint: AF32A6DCD709EDCC90FF3AE159318371D898C7BE
    url: https://raw.githubusercontent.com/sithanos/alucard/main/assets/pgp_keys.asc

  # artifacthub.io/images: |
  #   - name: img1
  #     image: repo/img1:1.0.0
  #     platforms:
  #       - linux/amd64
  #   - name: img2
  #     image: repo/img2:2.0.0
  #     whitelisted: true
  #     platforms:
  #       - linux/amd64
  # artifacthub.io/screenshots: |
  #   - title: Sample screenshot 1
  #     url: https://example.com/screenshot1.jpg
  #   - title: Sample screenshot 2
  #     url: https://example.com/screenshot2.jpg       