name: ArtifactHub Lint and Test
on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

permissions:
  contents: read

jobs:
  lint-test:
    runs-on: ubuntu-latest
    continue-on-error: false
    container:
      image: artifacthub/ah
      options: --user 1001
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Run ah lint
        working-directory: ./charts/alucard
        run: ah lint
