name: ArtifactHub Release Charts

on:
  push:
    # tags:
    #   - 'alucard-[0-9]+.[0-9]+.[0-9]+'
    #   - 'alucard-[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'
    branches:
      - "*"
      # - [main]
  # pull_request:
  #   branches:
  #     - "*"

jobs:

  # Lint and Test HelmCharts
  stage-lint-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read    
    continue-on-error: false
    container:
      image: artifacthub/ah
      options: --user 1001
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Run ah lint
        working-directory: ./charts/alucard
        run: ah lint

  # Release into ArtifactHub
  stage-publisher:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: stage-lint-test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$USER_NAME"
          git config user.email "$USER_EMAIL"

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.USER_TOKEN }}"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:          
          charts_dir: charts/alucard
          config: charts/assets/cr.yaml
          mark_as_latest: true
          pages_branch: main
          skip_existing: true
          skip_packaging: false
          skip_upload: false
        env:
          CR_TOKEN: "${{ secrets.USER_TOKEN }}"
